/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-12-08 02:49:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detailinforuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Documents/LuanSu/CNTT/HK5/Web/Project/web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Selling/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1695140474521L));
    _jspx_dependants.put("/common/taglist.jsp", Long.valueOf(1701766146721L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Documents/LuanSu/CNTT/HK5/Web/Project/web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Selling/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt-1_0-rt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1695790380415L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Documents/LuanSu/CNTT/HK5/Web/Project/web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Selling/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Documents/LuanSu/CNTT/HK5/Web/Project/web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Selling/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>chi tiết khách hàng </title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<section style=\"background-color: #eee;\">\r\n");
      out.write("  <div class=\"container py-5\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <nav aria-label=\"breadcrumb\" class=\"bg-light rounded-3 p-3 mb-4\">\r\n");
      out.write("          <ol class=\"breadcrumb mb-0\">\r\n");
      out.write("            <li class=\"breadcrumb-item active\" aria-current=\"page\">Chi tiết thông tin khách hàng</li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-4\">\r\n");
      out.write("        <div class=\"card mb-4\">\r\n");
      out.write("          <div class=\"card-body text-center\">\r\n");
      out.write("            <img src=\"https://scontent.fsgn7-1.fna.fbcdn.net/v/t39.30808-6/357053034_814960390037893_4922475779121350488_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=efb6e6&_nc_eui2=AeF5HXwEGNMOPAGrytHpFsrR_aLOXQRBb7r9os5dBEFvuq1yibYhcbMKiV2CqFcBHaVpuYriGC2v8DMoF6Nbu4wB&_nc_ohc=Ze3ZaC8Fg1MAX9TG622&_nc_oc=AQmDWUE6_UmimeSiZ2jirGF78bMaWn8SsKj91n1Ww_KGUbXwiKAj3EL5_Xtj4yiHMKSNdJC5OZuK6Owbhrs6JfIF&_nc_ht=scontent.fsgn7-1.fna&oh=00_AfDd4v0R2q3tAdPWQOOKi9RUuY7XoWJkZjUWeP86-vEZ3A&oe=65746821\" alt=\"avatar\"\r\n");
      out.write("              class=\"rounded-circle img-fluid\" style=\"width: 150px;\">\r\n");
      out.write("            <h5 class=\"my-3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.customerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("            <p class=\"text-muted mb-4\">ID: <span style=\"color: Blue \">113388</span> </p>\r\n");
      out.write("            <div class=\"d-flex justify-content-center mb-2\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-primary\">Quay lại</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card mb-4 mb-lg-0\">\r\n");
      out.write("          <div class=\"card-body p-0\">\r\n");
      out.write("            <ul class=\"list-group list-group-flush rounded-3\">\r\n");
      out.write("              <li class=\"list-group-item d-flex justify-content-between align-items-center p-3\">\r\n");
      out.write("                <i class=\"fa-solid fa-repeat\"></i>\r\n");
      out.write("                <p class=\"mb-0\">Phản hồi</p>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-group-item d-flex justify-content-between align-items-center p-3\">\r\n");
      out.write("                <i class=\"fa-regular fa-star\" style=\"color: #333333;\"></i>\r\n");
      out.write("                <p class=\"mb-0\">Đánh giá</p>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-group-item d-flex justify-content-between align-items-center p-3\">\r\n");
      out.write("                <i class=\"fa-solid fa-question\" style=\"color: #333333;\"></i>\r\n");
      out.write("                <p class=\"mb-0\">Trợ Giúp</p>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-8\">\r\n");
      out.write("        <div class=\"card mb-4\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <p class=\"mb-0\">Họ tên</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <p class=\"text-muted mb-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.customerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <p class=\"mb-0\">Email</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <p class=\"text-muted mb-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.mail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <p class=\"mb-0\">Số điện thoại</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <p class=\"text-muted mb-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <p class=\"mb-0\">Ngày sinh</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <p class=\"text-muted mb-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.birthday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-sm-3\">\r\n");
      out.write("                <p class=\"mb-0\">Địa chỉ</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-sm-9\">\r\n");
      out.write("                <p class=\"text-muted mb-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customer.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-20\">\r\n");
      out.write("            <div class=\"card mb-4 mb-md-0\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <p class=\"mb-4\"><span class=\"text-primary font-italic me-1\" style=\"font-weight: bold\">Tình Trạng Đơn Hàng</span> \r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"mb-1\" style=\"font-size: .77rem;\">Tất Cả</p>\r\n");
      out.write("                <div class=\"progress rounded\" style=\"height: 5px;\">\r\n");
      out.write("                  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 80%\" aria-valuenow=\"80\"\r\n");
      out.write("                    aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"mt-4 mb-1\" style=\"font-size: .77rem;\">Đã Trả</p>\r\n");
      out.write("                <div class=\"progress rounded\" style=\"height: 5px;\">\r\n");
      out.write("                  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 72%\" aria-valuenow=\"72\"\r\n");
      out.write("                    aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"mt-4 mb-1\" style=\"font-size: .77rem;\">Gửi Hàng</p>\r\n");
      out.write("                <div class=\"progress rounded\" style=\"height: 5px;\">\r\n");
      out.write("                  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 89%\" aria-valuenow=\"89\"\r\n");
      out.write("                    aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"mt-4 mb-1\" style=\"font-size: .77rem;\">Nhận</p>\r\n");
      out.write("                <div class=\"progress rounded\" style=\"height: 5px;\">\r\n");
      out.write("                  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 55%\" aria-valuenow=\"55\"\r\n");
      out.write("                    aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"mt-4 mb-1\" style=\"font-size: .77rem;\">Hoàn Thành</p>\r\n");
      out.write("                <div class=\"progress rounded mb-2\" style=\"height: 5px;\">\r\n");
      out.write("                  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 66%\" aria-valuenow=\"66\"\r\n");
      out.write("                    aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"mt-4 mb-1\" style=\"font-size: .77rem;\">Đã Hủy</p>\r\n");
      out.write("                <div class=\"progress rounded mb-2\" style=\"height: 5px;\">\r\n");
      out.write("                  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 6%\" aria-valuenow=\"6\"\r\n");
      out.write("                    aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"mt-4 mb-1\" style=\"font-size: .77rem;\">Hoàn lại tiền</p>\r\n");
      out.write("                <div class=\"progress rounded mb-2\" style=\"height: 5px;\">\r\n");
      out.write("                  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 16%\" aria-valuenow=\"16\"\r\n");
      out.write("                    aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
