/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-12-07 19:18:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class listorder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--  -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Danh sách Order</title>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/templates/admin/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!--  content -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/boxicons/2.1.0/css/boxicons.min.css\" integrity=\"sha512-pVCM5+SN2+qwj36KonHToF2p1oIvoU3bsqxphdOIWMYmgr4ZqD3t5DjKvvetKhXGc/ZG5REYTT6ltKfExEei/Q==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css\" integrity=\"sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=\" crossorigin=\"anonymous\" />\r\n");
      out.write("\r\n");
      out.write("<div class=\"list d-flex justify-content-center align-items-center\">\r\n");
      out.write("<button type=\"button\" class=\"btn btn-outline-primary\">Khách Hàng</button>\r\n");
      out.write("<button type=\"button\" class=\"btn btn-outline-primary\">Nhân Viên</button>\r\n");
      out.write("<button type=\"button\" class=\"btn btn-outline-primary\"><a href=\"/views/admin/listshipper.jsp\">Shipper</a> </button>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row align-items-center\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <h5 class=\"card-title\">Thông tin khách hàng <span class=\"text-muted fw-normal ms-2\">(834)</span></h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("            <div class=\"\">\r\n");
      out.write("                <div class=\"table-responsive\">\r\n");
      out.write("                    <table class=\"table project-list-table table-nowrap align-middle table-borderless\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"col\" class=\"ps-4\" style=\"width: 50px;\">\r\n");
      out.write("                                    <div class=\"form-check font-size-16\"><input type=\"checkbox\" class=\"form-check-input\" id=\"contacusercheck\" /><label class=\"form-check-label\" for=\"contacusercheck\"></label></div>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <th scope=\"col\">Tài khoản</th>\r\n");
      out.write("                                <th scope=\"col\">Số Lượng đơn mua</th>\r\n");
      out.write("                                <th scope=\"col\">Email</th>\r\n");
      out.write("                                <th scope=\"col\">Số điện thoại</th>\r\n");
      out.write("                                <th scope=\"col\" style=\"width: 200px;\">Lựa chọn</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\" class=\"ps-4\">\r\n");
      out.write("                                    <div class=\"form-check font-size-16\"><input type=\"checkbox\" class=\"form-check-input\" id=\"contacusercheck1\" /><label class=\"form-check-label\" for=\"contacusercheck1\"></label></div>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <td><img src=\"https://scontent.fsgn3-1.fna.fbcdn.net/v/t39.30808-6/357053034_814960390037893_4922475779121350488_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeF5HXwEGNMOPAGrytHpFsrR_aLOXQRBb7r9os5dBEFvuq1yibYhcbMKiV2CqFcBHaVpuYriGC2v8DMoF6Nbu4wB&_nc_ohc=-yKX52Urdn0AX8U0a-v&_nc_oc=AQlI2Ns9XLRTfcBwWgD0RHgOWIUMetQvlk_-r_YQaQQu_hub_sENbxLo6HLTTSsB0Ug&_nc_ht=scontent.fsgn3-1.fna&oh=00_AfAkwmC6el-T5G0ksuVne_5NYx6l7Dvg2p6XioTa2XhQgQ&oe=6556BE61\" alt=\"\" class=\"avatar-sm rounded-circle me-2\" /><a href=\"#\" class=\"text-body\">Simon Ryles</a></td>\r\n");
      out.write("                                <td><span class=\"badge badge-soft-success mb-0\">20</span></td>\r\n");
      out.write("                                <td>SimonRyles@minible.com</td>\r\n");
      out.write("                                <td>0382737462</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\" class=\"px-2 text-primary\"><i class=\"bx bx-pencil font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Delete\" class=\"px-2 text-danger\"><i class=\"bx bx-trash-alt font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\" class=\"ps-4\">\r\n");
      out.write("                                    <div class=\"form-check font-size-16\"><input type=\"checkbox\" class=\"form-check-input\" id=\"contacusercheck2\" /><label class=\"form-check-label\" for=\"contacusercheck2\"></label></div>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <td><img src=\"https://scontent.fsgn4-1.fna.fbcdn.net/v/t39.30808-6/339908861_207526681891832_1233331276264573363_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeFJ4anPj9NtC_ZXyKQgLXW8YbiVsfA75rBhuJWx8DvmsBnd5OhM8q4r_k68Qy8JcoAD3jsoMp5iaPTcmvmLo366&_nc_ohc=60IqQ4L2MlMAX-Q0_O-&_nc_ht=scontent.fsgn4-1.fna&oh=00_AfAi3yPUfZzd37VSX88cYg6IjtgIqrEZHDrPfEA7jUM6oA&oe=6555B210\" alt=\"\" class=\"avatar-sm rounded-circle me-2\" /><a href=\"#\" class=\"text-body\">Marion Walker</a></td>\r\n");
      out.write("                                <td><span class=\"badge badge-soft-info mb-0\">134</span></td>\r\n");
      out.write("                                <td>MarionWalker@minible.com</td>\r\n");
      out.write("                                <td>0927366354</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\" class=\"px-2 text-primary\"><i class=\"bx bx-pencil font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Delete\" class=\"px-2 text-danger\"><i class=\"bx bx-trash-alt font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\" class=\"ps-4\">\r\n");
      out.write("                                    <div class=\"form-check font-size-16\"><input type=\"checkbox\" class=\"form-check-input\" id=\"contacusercheck3\" /><label class=\"form-check-label\" for=\"contacusercheck3\"></label></div>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"avatar-sm d-inline-block me-2\">\r\n");
      out.write("                                        <div class=\"avatar-title bg-soft-primary rounded-circle text-primary\"><i class=\"mdi mdi-account-circle m-0\"></i></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <a href=\"#\" class=\"text-body\">Frederick White</a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><span class=\"badge badge-soft-danger mb-0\">123</span></td>\r\n");
      out.write("                                <td>FrederickWhite@minible.com</td>\r\n");
      out.write("                                <td>0182736362</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\" class=\"px-2 text-primary\"><i class=\"bx bx-pencil font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Delete\" class=\"px-2 text-danger\"><i class=\"bx bx-trash-alt font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\" class=\"ps-4\">\r\n");
      out.write("                                    <div class=\"form-check font-size-16\"><input type=\"checkbox\" class=\"form-check-input\" id=\"contacusercheck4\" /><label class=\"form-check-label\" for=\"contacusercheck4\"></label></div>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <td><img src=\"https://scontent.fsgn3-1.fna.fbcdn.net/v/t39.30808-6/278383019_526100198923915_1078175830879600888_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeGHwP6HRGDY_4895ALBlkHfcnYZpPz58SJydhmk_PnxIg-70u3FewryiLOAThQuMz99kTssKbILIW1KzMPfPbrk&_nc_ohc=S3Nvh0N-XO8AX8yPhcc&_nc_oc=AQkceypuViFX6WSYrB1OR_qaFvMigExEN8oSoLhm3SoFagW9nfMByc38HF13UeZVHi8&_nc_ht=scontent.fsgn3-1.fna&oh=00_AfCzfjP_ddvqmEX6lJ2NB2urUgmMBklmTYxH4UI3XjHSrw&oe=655713B8\" alt=\"\" class=\"avatar-sm rounded-circle me-2\" /><a href=\"#\" class=\"text-body\">Shanon Marvin</a></td>\r\n");
      out.write("                                <td><span class=\"badge badge-soft-primary mb-0\">73643</span></td>\r\n");
      out.write("                                <td>ShanonMarvin@minible.com</td>\r\n");
      out.write("                                <td>0299283777</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\" class=\"px-2 text-primary\"><i class=\"bx bx-pencil font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Delete\" class=\"px-2 text-danger\"><i class=\"bx bx-trash-alt font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\" class=\"ps-4\">\r\n");
      out.write("                                    <div class=\"form-check font-size-16\"><input type=\"checkbox\" class=\"form-check-input\" id=\"contacusercheck5\" /><label class=\"form-check-label\" for=\"contacusercheck5\"></label></div>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"avatar-sm d-inline-block me-2\">\r\n");
      out.write("                                        <div class=\"avatar-title bg-soft-primary rounded-circle text-primary\"><i class=\"mdi mdi-account-circle m-0\"></i></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <a href=\"#\" class=\"text-body\">Mark Jones</a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td><span class=\"badge badge-soft-info mb-0\">1736</span></td>\r\n");
      out.write("                                <td>MarkJones@minible.com</td>\r\n");
      out.write("                                <td>0915226353</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\" class=\"px-2 text-primary\"><i class=\"bx bx-pencil font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Delete\" class=\"px-2 text-danger\"><i class=\"bx bx-trash-alt font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\" class=\"ps-4\">\r\n");
      out.write("                                    <div class=\"form-check font-size-16\"><input type=\"checkbox\" class=\"form-check-input\" id=\"contacusercheck6\" /><label class=\"form-check-label\" for=\"contacusercheck6\"></label></div>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <td><img src=\"https://scontent.fsgn4-1.fna.fbcdn.net/v/t39.30808-6/381207883_858099802390618_7125856891839006304_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeGANIKNYKpVhbB0oKbOr2s-msfY58s5fO6ax9jnyzl87j1E6dWlMa25NdemG9rMfN0Goj5RL--Bqt7rWYU9qtip&_nc_ohc=_I3j7QaO_MoAX_ZMfKm&_nc_ht=scontent.fsgn4-1.fna&oh=00_AfD93ljfad4fLBdWClNPHWMXM-IlytphQ2Wf2xKjV4QVyA&oe=6556326E\" alt=\"\" class=\"avatar-sm rounded-circle me-2\" /><a href=\"#\" class=\"text-body\">Janice Morgan</a></td>\r\n");
      out.write("                                <td><span class=\"badge badge-soft-primary mb-0\">34</span></td>\r\n");
      out.write("                                <td>JaniceMorgan@minible.com</td>\r\n");
      out.write("                                <td>0788736272</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\" class=\"px-2 text-primary\"><i class=\"bx bx-pencil font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Delete\" class=\"px-2 text-danger\"><i class=\"bx bx-trash-alt font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\" class=\"ps-4\">\r\n");
      out.write("                                    <div class=\"form-check font-size-16\"><input type=\"checkbox\" class=\"form-check-input\" id=\"contacusercheck7\" /><label class=\"form-check-label\" for=\"contacusercheck7\"></label></div>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <td><img src=\"https://bootdey.com/img/Content/avatar/avatar1.png\" alt=\"\" class=\"avatar-sm rounded-circle me-2\" /><a href=\"#\" class=\"text-body\">Patrick Petty</a></td>\r\n");
      out.write("                                <td><span class=\"badge badge-soft-danger mb-0\">1627</span></td>\r\n");
      out.write("                                <td>PatrickPetty@minible.com</td>\r\n");
      out.write("                                <td>0366484756</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\" class=\"px-2 text-primary\"><i class=\"bx bx-pencil font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Delete\" class=\"px-2 text-danger\"><i class=\"bx bx-trash-alt font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\" class=\"ps-4\">\r\n");
      out.write("                                    <div class=\"form-check font-size-16\"><input type=\"checkbox\" class=\"form-check-input\" id=\"contacusercheck8\" /><label class=\"form-check-label\" for=\"contacusercheck8\"></label></div>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <td><img src=\"https://bootdey.com/img/Content/avatar/avatar1.png\" alt=\"\" class=\"avatar-sm rounded-circle me-2\" /><a href=\"#\" class=\"text-body\">Marilyn Horton</a></td>\r\n");
      out.write("                                <td><span class=\"badge badge-soft-primary mb-0\">3637</span></td>\r\n");
      out.write("                                <td>MarilynHorton@minible.com</td>\r\n");
      out.write("                                <td>0373646362</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\" class=\"px-2 text-primary\"><i class=\"bx bx-pencil font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Delete\" class=\"px-2 text-danger\"><i class=\"bx bx-trash-alt font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"row\" class=\"ps-4\">\r\n");
      out.write("                                    <div class=\"form-check font-size-16\"><input type=\"checkbox\" class=\"form-check-input\" id=\"contacusercheck9\" /><label class=\"form-check-label\" for=\"contacusercheck9\"></label></div>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <td><img src=\"https://bootdey.com/img/Content/avatar/avatar1.png\" alt=\"\" class=\"avatar-sm rounded-circle me-2\" /><a href=\"#\" class=\"text-body\">Neal Womack</a></td>\r\n");
      out.write("                                <td><span class=\"badge badge-soft-success mb-0\">99</span></td>\r\n");
      out.write("                                <td>NealWomack@minible.com</td>\r\n");
      out.write("                                <td>0192737272</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <ul class=\"list-inline mb-0\">\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\" class=\"px-2 text-primary\"><i class=\"bx bx-pencil font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"list-inline-item\">\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Delete\" class=\"px-2 text-danger\"><i class=\"bx bx-trash-alt font-size-18\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row g-0 align-items-center pb-4\">\r\n");
      out.write("        <div class=\"col-sm-6\">\r\n");
      out.write("            <div><p class=\"mb-sm-0\">Hiển thị 1 đến 10 trong 57 mục</p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6\">\r\n");
      out.write("            <div class=\"float-sm-end\">\r\n");
      out.write("                <ul class=\"pagination mb-sm-0\">\r\n");
      out.write("                    <li class=\"page-item disabled\">\r\n");
      out.write("                        <a href=\"#\" class=\"page-link\"><i class=\"mdi mdi-chevron-left\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"page-item active\"><a href=\"#\" class=\"page-link\">1</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">2</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">3</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">4</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">5</a></li>\r\n");
      out.write("                    <li class=\"page-item\">\r\n");
      out.write("                        <a href=\"#\" class=\"page-link\"><i class=\"mdi mdi-chevron-right\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("	<!-- end content-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
