/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-12-08 02:33:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Giỏ hàng</title>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/templates/user/css/stylecart.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <section class=\"h-100\" style=\"background-color: #eee;\">\r\n");
      out.write("  <div class=\"container h-100 py-5\">\r\n");
      out.write("    <div class=\"row d-flex justify-content-center align-items-center h-100\">\r\n");
      out.write("      <div class=\"col-10\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("          <h3 class=\"fw-normal mb-0 text-black\">Shopping Cart</h3>\r\n");
      out.write("                    <div>\r\n");
      out.write("            <p class=\"mb-0\"><span class=\"text-muted\">Tổng(4)</span></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"card rounded-3 mb-4\">\r\n");
      out.write("          <div class=\"card-body p-4\">\r\n");
      out.write("            <div class=\"row d-flex justify-content-between align-items-center\">\r\n");
      out.write("              <div class=\"col-md-2 col-lg-2 col-xl-2\">\r\n");
      out.write("                <img\r\n");
      out.write("                  src=\"https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2F30608%2F30608.png%3Fversion%3D1594225801&w=720&bc=%23f5f5f5&ib=%23f5f5f5&h=720&q=70\"\r\n");
      out.write("                  class=\"img-fluid rounded-3\" alt=\"Cotton T-shirt\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-3 col-xl-3\">\r\n");
      out.write("                <p class=\"lead fw-normal mb-2\">Eau de Parfum</p>\r\n");
      out.write("                <p><span class=\"text-muted\">Size: </span>M <span class=\"text-muted\">Color: </span>yellow</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-3 col-xl-2 d-flex\">\r\n");
      out.write("                <button class=\"btn btn-link px-2\"\r\n");
      out.write("                  onclick=\"this.parentNode.querySelector('input[type=number]').stepDown()\">\r\n");
      out.write("                  <i class=\"fas fa-minus\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <input id=\"form1\" min=\"0\" name=\"quantity\" value=\"2\" type=\"number\"\r\n");
      out.write("                  class=\"form-control form-control-sm\" />\r\n");
      out.write("\r\n");
      out.write("                <button class=\"btn btn-link px-2\"\r\n");
      out.write("                  onclick=\"this.parentNode.querySelector('input[type=number]').stepUp()\">\r\n");
      out.write("                  <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-2 col-xl-2 offset-lg-1\">\r\n");
      out.write("                <h5 class=\"mb-0\">$499.00</h5>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-1 col-lg-1 col-xl-1 text-end\">\r\n");
      out.write("                <a href=\"#!\" class=\"text-danger\"><i class=\"fas fa-trash fa-lg\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card rounded-3 mb-4\">\r\n");
      out.write("          <div class=\"card-body p-4\">\r\n");
      out.write("            <div class=\"row d-flex justify-content-between align-items-center\">\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"col-md-2 col-lg-2 col-xl-2\">\r\n");
      out.write("                <img\r\n");
      out.write("                  src=\"https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2F29696%2F29696.png%3Fversion%3D1607364000&w=720&bc=%23f5f5f5&ib=%23f5f5f5&h=720&q=70\"\r\n");
      out.write("                  class=\"img-fluid rounded-3\" alt=\"Cotton T-shirt\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-3 col-xl-3\">\r\n");
      out.write("                <p class=\"lead fw-normal mb-2\">Nuit Eau de Parfum for her</p>\r\n");
      out.write("                <p><span class=\"text-muted\">Size: </span>M <span class=\"text-muted\">Color: </span>Grey</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-3 col-xl-2 d-flex\">\r\n");
      out.write("                <button class=\"btn btn-link px-2\"\r\n");
      out.write("                  onclick=\"this.parentNode.querySelector('input[type=number]').stepDown()\">\r\n");
      out.write("                  <i class=\"fas fa-minus\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <input id=\"form1\" min=\"0\" name=\"quantity\" value=\"2\" type=\"number\"\r\n");
      out.write("                  class=\"form-control form-control-sm\" />\r\n");
      out.write("\r\n");
      out.write("                <button class=\"btn btn-link px-2\"\r\n");
      out.write("                  onclick=\"this.parentNode.querySelector('input[type=number]').stepUp()\">\r\n");
      out.write("                  <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-2 col-xl-2 offset-lg-1\">\r\n");
      out.write("                <h5 class=\"mb-0\">$89.00</h5>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-1 col-lg-1 col-xl-1 text-end\">\r\n");
      out.write("                <a href=\"#!\" class=\"text-danger\"><i class=\"fas fa-trash fa-lg\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card rounded-3 mb-4\">\r\n");
      out.write("          <div class=\"card-body p-4\">\r\n");
      out.write("            <div class=\"row d-flex justify-content-between align-items-center\">\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"col-md-2 col-lg-2 col-xl-2\">\r\n");
      out.write("                <img\r\n");
      out.write("                  src=\"https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2F35653%2F35653.png%3Fversion%3D1607561110&w=720&bc=%23f5f5f5&ib=%23f5f5f5&h=720&q=70\"\r\n");
      out.write("                  class=\"img-fluid rounded-3\" alt=\"Cotton T-shirt\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-3 col-xl-3\">\r\n");
      out.write("                <p class=\"lead fw-normal mb-2\">Rose Nectar Hand & Body Wash</p>\r\n");
      out.write("                <p><span class=\"text-muted\">Size: </span>M <span class=\"text-muted\">Color: </span>Grey</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-3 col-xl-2 d-flex\">\r\n");
      out.write("                <button class=\"btn btn-link px-2\"\r\n");
      out.write("                  onclick=\"this.parentNode.querySelector('input[type=number]').stepDown()\">\r\n");
      out.write("                  <i class=\"fas fa-minus\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <input id=\"form1\" min=\"0\" name=\"quantity\" value=\"2\" type=\"number\"\r\n");
      out.write("                  class=\"form-control form-control-sm\" />\r\n");
      out.write("\r\n");
      out.write("                <button class=\"btn btn-link px-2\"\r\n");
      out.write("                  onclick=\"this.parentNode.querySelector('input[type=number]').stepUp()\">\r\n");
      out.write("                  <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-2 col-xl-2 offset-lg-1\">\r\n");
      out.write("                <h5 class=\"mb-0\">$76.00</h5>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-1 col-lg-1 col-xl-1 text-end\">\r\n");
      out.write("                <a href=\"#!\" class=\"text-danger\"><i class=\"fas fa-trash fa-lg\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card rounded-3 mb-4\">\r\n");
      out.write("          <div class=\"card-body p-4\">\r\n");
      out.write("            <div class=\"row d-flex justify-content-between align-items-center\">\r\n");
      out.write("            \r\n");
      out.write("              \r\n");
      out.write("              <div class=\"col-md-2 col-lg-2 col-xl-2\">\r\n");
      out.write("                <img\r\n");
      out.write("                  src=\"https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2F42519%2F42519.png%3Fversion%3D1605800700&w=720&bc=%23f5f5f5&ib=%23f5f5f5&h=720&q=70\"\r\n");
      out.write("                  class=\"img-fluid rounded-3\" alt=\"Cotton T-shirt\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-3 col-xl-3\">\r\n");
      out.write("                <p class=\"lead fw-normal mb-2\">Rose Nectar Hand & Body Cream</p>\r\n");
      out.write("                <p><span class=\"text-muted\">Size: </span>M <span class=\"text-muted\">Color: </span>Grey</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-3 col-xl-2 d-flex\">\r\n");
      out.write("                <button class=\"btn btn-link px-2\"\r\n");
      out.write("                  onclick=\"this.parentNode.querySelector('input[type=number]').stepDown()\">\r\n");
      out.write("                  <i class=\"fas fa-minus\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <input id=\"form1\" min=\"0\" name=\"quantity\" value=\"2\" type=\"number\"\r\n");
      out.write("                  class=\"form-control form-control-sm\" />\r\n");
      out.write("\r\n");
      out.write("                <button class=\"btn btn-link px-2\"\r\n");
      out.write("                  onclick=\"this.parentNode.querySelector('input[type=number]').stepUp()\">\r\n");
      out.write("                  <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 col-lg-2 col-xl-2 offset-lg-1\">\r\n");
      out.write("                <h5 class=\"mb-0\">$49.00</h5>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-1 col-lg-1 col-xl-1 text-end\">\r\n");
      out.write("                <a href=\"#!\" class=\"text-danger\"><i class=\"fas fa-trash fa-lg\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   <div class=\"row g-0 align-items-center pb-4\">\r\n");
      out.write("        <div class=\"col-sm-6\">\r\n");
      out.write("            <div><p class=\"mb-sm-0\">Hiển thị 1 đến 10 trong 57 mục</p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-6\">\r\n");
      out.write("            <div class=\"float-sm-end\">\r\n");
      out.write("                <ul class=\"pagination mb-sm-0\">\r\n");
      out.write("                    <li class=\"page-item disabled\">\r\n");
      out.write("                        <a href=\"#\" class=\"page-link\"><i class=\"mdi mdi-chevron-left\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"page-item active\"><a href=\"#\" class=\"page-link\">1</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">2</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">3</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">4</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a href=\"#\" class=\"page-link\">5</a></li>\r\n");
      out.write("                    <li class=\"page-item\">\r\n");
      out.write("                        <a href=\"#\" class=\"page-link\"><i class=\"mdi mdi-chevron-right\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card rounded-3 mb-4\">\r\n");
      out.write("      <div class=\"card-body p-4\">\r\n");
      out.write("          <div class=\"row d-flex justify-content-between align-items-center\"> \r\n");
      out.write("              <div class=\"card-body p-4 d-flex flex-row\">\r\n");
      out.write("                  <div></div>\r\n");
      out.write("                  <!-- Thêm thẻ div cho tổng tiền thanh toán -->\r\n");
      out.write("                  <div class=\"total-payment-container\">\r\n");
      out.write("                      <div class=\"total-payment\">Tổng tiền thanh toán: <span class=\"amount\">$100.00</span></div>\r\n");
      out.write("                      <button type=\"button\" class=\"btn btn-outline-primary btn-block btn-lg\">Thanh toán</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
